// module/constants/tarot-images.mjs
// АВТОГЕНЕРАЦИЯ: карта № карты (1–78) → путь к арту в assets/tarot-card.
// Ключ — число в скобках (N) в имени файла. Пересоздать при добавлении/переименовании файлов.
export const TAROT_IMAGES = {
  1: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/0 – Пилигрим (1).jpg",
  2: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/I – Астропат (2).jpg",
  3: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/II – Пророк (3).jpg",
  4: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/III – Святая Терра (4).jpg",
  5: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/IV – Бог Император (5).jpg",
  6: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/V – Экклезиарх (6).jpg",
  7: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/VI – Единство (7).jpg",
  8: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/VII – Крестоносец (8).jpg",
  9: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/VIII – Святая (9).jpg",
  10: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/IX – Предсказатель (10).jpg",
  11: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/X – Человек (11).jpg",
  12: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XI – Титан (12).jpg",
  13: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XII – Мученик (13).jpg",
  14: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XIII – Жнец (14).jpg",
  15: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XIV – Империум (15).jpg",
  16: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XV – Демон (16).jpg",
  17: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XVI – Космический Скиталец (17).jpg",
  18: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XVII – Астрономикон (18).jpg",
  19: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XVIII – Имматериум (19).jpg",
  20: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XIX – Золотой Трон (20).jpg",
  21: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XX – Судья (21).jpg",
  22: "systems/warhammer-dbc/assets/tarot-card/Major Arcana/XXI – Галактика (22).jpg",
  23: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/Мастер – Воитель (23).jpg",
  24: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/Лорд – Регент (24).jpg",
  25: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/Чемпион – Примарх (25).jpg",
  26: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/Слуга – Кустодий (26).jpg",
  27: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/Туз – Инквизитор (27).jpg",
  28: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/II – Писарь (28).jpg",
  29: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/III – Администратор (29).jpg",
  30: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/IV – Арбитр (30).jpg",
  31: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/V – Санкционированный Псайкер (31).jpg",
  32: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/VI – Техножрец(32).jpg",
  33: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/VII – Сестра Битвы (33).jpg",
  34: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/VIII – Ассассин (34).jpg",
  35: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/IX – Проповедник (35).jpg",
  36: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Adeptio/X – Ангел Смерти (36).jpg",
  37: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/Мастер – Предатель (37).jpg",
  38: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/Лорд – Узурпатор (38).jpg",
  39: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/Чемпион – Ренегат (39).jpg",
  40: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/Слуга – Бездушный (40).jpg",
  41: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/Туз – Арлекин (41).jpg",
  42: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/II – Ксенос (42).jpg",
  43: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/III – Еретик (43).jpg",
  44: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/IV – Мутант (44).jpg",
  45: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/V – Ведьма (45).jpg",
  46: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/VI – Подлая Змея (46).jpg",
  47: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/VII – Нечистый (47).jpg",
  48: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/VIII – Владыка Крови (48).jpg",
  49: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/IX – Повелитель Перемен (49).jpg",
  50: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Discordia/X – Око Ужаса (50).jpg",
  51: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/Мастер – Лорд–Милитант (51).jpg",
  52: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/Лорд – Магистр Ордена (52).jpg",
  53: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/Чемпион – Вольный Торговец (53).jpg",
  54: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/Слуга – Патернова (54).jpg",
  55: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/Туз – Незнакомец (55).jpg",
  56: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/II – Солдат (56).jpg",
  57: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/III – Сержант (57).jpg",
  58: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/IV – Офицер (58).jpg",
  59: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/V – Капитан (59).jpg",
  60: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/VI – Генерал (60).jpg",
  61: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/VII – Эксплоратор (61).jpg",
  62: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/VIII – Навигатор (62).jpg",
  63: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/IX – Миссионер (63).jpg",
  64: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Excuteria/X – Архимагос (64).jpg",
  65: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/Мастер – Высший Лорд (65).jpg",
  66: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/Лорд – Губернатор (66).jpg",
  67: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/Чемпион – Кардинал (67).jpg",
  68: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/Слуга – Сенатор (68).jpg",
  69: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/Туз – Дикарь (69).jpg",
  70: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/II – Гражданин (70).jpg",
  71: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/III – Ремесленник (71).jpg",
  72: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/IV – Гильдмастер (72).jpg",
  73: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/V – Дворянин (73).jpg",
  74: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/VI – Фабрикатор (74).jpg",
  75: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/VII – Оратор (75).jpg",
  76: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/VIII – Коллектор (76).jpg",
  77: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/IX – Епископ (77).jpg",
  78: "systems/warhammer-dbc/assets/tarot-card/Minor Arcana Mandatio/X – Консул (78).jpg",
};
