// Таблица перевода опознания по имени на ключ Возможности (wdbc-iadw).
// Только те вызовы, что спрашивают АКТОРА («есть ли у него X»). Вопросы к
// конкретному предмету («этот ли предмет X») сюда не входят — ключ Возможности
// живёт на акторе и вернуть сам предмет не может.
//
// key    — ключ реестра module/constants/capabilities.mjs
// name   — имя, по которому опознавали (одна половина, не пара)
// types  — тип(ы) предмета-носителя для проверки по имени
// label  — подпись для реестра и панели «Возможности сейчас»
// reader — где ключ читают
export const ABILITIES = [
  { key: "ability.adjutant", name: "Adjutant", types: "talent",
    label: "Адъютант: даёт своему Командиру переброс, а не себе",
    reader: "module/rules/adjutant.mjs hasAdjutant()" },
  { key: "ability.adrenalineRush", name: "Adrenaline Rush", types: "talent",
    label: "Прилив Адреналина: раз за бой за Очко Бесчестия вернуть все потраченные Реакции",
    reader: "module/combat/adrenaline-rush.mjs hasAdrenalineRush()" },
  { key: "ability.assassinStrike", name: "Assassin Strike", types: "talent",
    label: "Удар Ассасина: раз в Раунд после рукопашной атаки тест Акробатики и отскок",
    reader: "module/combat/assassin-strike.mjs hasAssassinStrike()" },
  { key: "ability.avatarOfSlaughter", name: "Avatar of Slaughter", types: "trait",
    label: "Аватар Резни: раз за бой отметить противника кровожадностью",
    reader: "module/combat/avatar-of-slaughter.mjs hasAvatarOfSlaughter()" },
  { key: "ability.boneSong", name: "Bone Song", types: "talent",
    label: "Костяная Песня: Полное действие — починка психокостяной техники в радиусе W м",
    reader: "module/combat/bone-song.mjs hasBoneSong()" },
  { key: "ability.bowToTheAudience", name: "Bow to the Audience", types: "talent",
    label: "Поклон Публике: за 3 ОД тест Внимания против нескольких противников сразу",
    reader: "module/combat/bow-to-audience.mjs hasBowToTheAudience()" },
  { key: "ability.butchersNails", name: "Butcher's Nails", types: "trait",
    label: "Гвозди Мясника: своя механика входа и выхода из Ярости",
    reader: "module/combat/frenzy.mjs hasButchersNails()" },
  { key: "ability.conjureWraith", name: "Conjure Wraith", types: "talent",
    label: "Вызвать Психокость: Полное действие — создать психокостяной предмет",
    reader: "module/combat/conjure-wraith.mjs hasConjureWraith()" },
  { key: "ability.dancingAmongTheFire", name: "Dancing Among The Fire", types: "talent",
    label: "Танец Среди Огня: преимущество при Уклонении",
    reader: "module/rules/dodge-advantage.mjs hasDancingAmongTheFire()" },
  { key: "ability.deadlyEffectiveness", name: "Deadly Effectiveness", types: "talent",
    label: "Смертоносная Эффективность: убийство после финта даёт +2 ОД и доп. атаку",
    reader: "module/combat/deadly-effectiveness.mjs hasDeadlyEffectiveness()" },
  { key: "ability.deathDance", name: "Death Dance", types: "talent",
    label: "Смертельный Танец: раз за битву перераспределить попадания натиска",
    reader: "module/combat/death-dance.mjs hasDeathDance()" },
  { key: "ability.determinationToFight", name: "Determination To Fight", types: "talent",
    label: "Решительность Сражаться: своя механика продолжения боя",
    reader: "module/rules/determination-to-fight.mjs hasDeterminationToFight()" },
  { key: "ability.dominator", name: "Dominator", types: "talent",
    label: "Покоритель: своя механика подчинения",
    reader: "module/rules/dominator.mjs hasDominator()" },
  { key: "ability.dreadWail", name: "Dread Wail", types: "trait",
    label: "Грозный Вопль: раз за бой за Очко Бесчестия усилить звуковое оружие брони",
    reader: "module/combat/dread-wail.mjs hasDreadWail()" },
  { key: "ability.electrovigour", name: "Electrovigour", types: "talent",
    label: "Электрорвение: своя механика Техномистика",
    reader: "module/rules/electrovigour.mjs hasElectrovigour()" },
  { key: "ability.enjoyment", name: "Enjoyment", types: "talent",
    label: "Наслаждение: Талант друкхари, своя механика на страданиях цели",
    reader: "module/combat/enjoyment.mjs hasEnjoyment()" },
  { key: "ability.eternalWarrior", name: "Eternal Warrior", types: "mutation",
    label: "Вечный Воин: смерть в Ярости даёт бесплатное Чудесное Спасение раз за сессию",
    reader: "module/combat/eternal-warrior.mjs hasEternalWarrior()" },
  { key: "ability.flipBelt", name: "Flip Belt", types: "gear",
    label: "Ремень Кувырков: бонус к тестам отскока и уклонения",
    reader: "module/combat/recoil-item-bonuses.mjs — бонус снаряжения к отскоку" },
  { key: "ability.frenzy", name: "Frenzy", types: "talent",
    label: "Ярость: вход в Ярость и выход по тесту W",
    reader: "module/combat/frenzy.mjs hasFrenzyTalent()" },
  { key: "ability.fullyArmed", name: "Fully Armed", types: "trait",
    label: "Во Всеоружии: своя механика владения оружием",
    reader: "module/combat/fully-armed.mjs hasFullyArmed()" },
  { key: "ability.halfStep", name: "Half-Step", types: "talent",
    label: "Полушаг: доступно действие Полушага в меню Движения",
    reader: "module/combat/movement-actions.mjs — пункт меню Движения" },
  { key: "ability.justTheLight", name: "Just the Light", types: "talent",
    label: "Лишь Свет: Талант Солитера, своя механика уклонения от внимания",
    reader: "module/combat/just-the-light.mjs hasJustTheLight()" },
  { key: "ability.lastActor", name: "Last Actor", types: ["talent", "trait"],
    label: "Последний Актёр: Талант Солитера, своя механика финального выхода",
    reader: "module/combat/last-actor.mjs hasLastActor()" },
  { key: "ability.lordOfTheExodites", name: "Lord of the Exodites", types: "trait",
    label: "Повелитель Экзодитов: бонусы к тестам Морали подчинённых",
    reader: "module/combat/lord-of-exodites.mjs hasLordOfTheExodites()" },
  { key: "ability.malearius", name: "Malearius", types: "talent",
    label: "Малеарий: с метеоритным молотом и лёгкой бронёй — двойные прыжки и доп. Реакция",
    reader: "module/combat/recoil-item-bonuses.mjs malaeriusActive()" },
  { key: "ability.oneAgainstAHundred", name: "One Against A Hundred", types: "talent",
    label: "Один Против Сотни: своя механика боя против многих",
    reader: "module/rules/one-against-a-hundred.mjs hasOneAgainstAHundred()" },
  { key: "ability.preservation", name: "Preservation", types: "talent",
    label: "Защита: Талант Певцов Кости, своя механика сохранения",
    reader: "module/combat/preservation.mjs hasPreservation()" },
  { key: "ability.reformationSong", name: "Reformation Song", types: "talent",
    label: "Песня Изменений: Талант Певцов Кости, перестройка психокости",
    reader: "module/combat/reformation-song.mjs hasReformationSong()" },
  { key: "ability.resplendentRaiment", name: "Resplendent Raiment", types: "mutation",
    label: "Блистательные Одеяния: Дар Слаанеш, своя механика облика",
    reader: "module/combat/resplendent-raiment.mjs hasResplendentRaiment()" },
  { key: "ability.salto", name: "Salto", types: "talent",
    label: "Сальто: бонус к отскоку и уклонению",
    reader: "module/combat/recoil-item-bonuses.mjs — бонус Таланта к отскоку" },
  { key: "ability.skillfulTorture", name: "Skillful Torture", types: "talent",
    label: "Искусная Пытка: своя механика допроса и Очков Боли",
    reader: "module/apps/skillful-torture.mjs hasSkillfulTorture()" },
  { key: "ability.snapshot", name: "Snapshot", types: "talent",
    label: "Выстрел Навскидку: стрельба реакцией без обычных штрафов",
    reader: "module/combat/snapshot.mjs hasSnapshot()" },
  { key: "ability.songOfSwiftness", name: "Song of Swiftness", types: "talent",
    label: "Песня Стремительности: Талант Певцов Кости, ускорение психокости",
    reader: "module/combat/song-of-swiftness.mjs hasSongOfSwiftness()" },
  { key: "ability.spiritTalk", name: "Spirit Talk", types: "talent",
    label: "Духовный Разговор: Талант Певцов Кости, речь с духами психокости",
    reader: "module/combat/spirit-talk.mjs hasSpiritTalk()" },
  { key: "ability.sweetCacophony", name: "Sweet Cacophony", types: "talent",
    label: "Сладкая Какофония: усиление Грозного Вопля",
    reader: "module/combat/dread-wail.mjs hasSweetCacophony()" },
  { key: "ability.middleOfTheHunt", name: "The Middle of the Hunt", types: "talent",
    label: "Середина Охоты: Талант Лесного Владыки, своя механика преследования",
    reader: "module/combat/middle-of-the-hunt.mjs hasMiddleOfTheHunt()" },
  { key: "ability.voiceOfGod", name: "Voice of God", types: "talent",
    label: "Глас Божий: своя механика приказов и Командования",
    reader: "module/combat/voice-of-god.mjs hasVoiceOfGod()" },
  { key: "ability.mechanicumImplants", name: "Импланты Механикум", types: "trait",
    label: "Импланты Механикум: на листе открывается блок Техножреца",
    reader: "module/sheets/character-context.mjs — context.hasMechImplants" }
];
